name: build docker image
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'kc.sh'
      - 'kc.java.security'
      - 'nginx.conf'
      - '.github/workflows/docker-image.yml'
      - '.dockerignore'
      - '!**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: doing checkout
      uses: actions/checkout@v4
    - name: build KeyCloak image
      run: docker buildx build . --file Dockerfile --tag ghcr.io/${REPOSITORY}/kc:${{ github.sha }} --tag ghcr.io/${REPOSITORY}/kc:latest --platform linux/amd64 --push --progress plain --target kc
      env:
        REPOSITORY: ${{ github.repository }}
    - name: build PROXY image
      run: docker buildx build . --file Dockerfile --tag ghcr.io/${REPOSITORY}/proxy:${{ github.sha }} --tag ghcr.io/${REPOSITORY}/proxy:latest --platform linux/amd64 --push --progress plain --target proxy
      env:
        REPOSITORY: ${{ github.repository }}

