name: build docker image
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/build.sh'
      - '**/deploy.sh'
      - '**/kc_cli.sh'
      - '**/kc.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: doing checkout
      uses: actions/checkout@v4
    - name: build image
      run: docker buildx build . --file Dockerfile --tag ghcr.io/${REPOSITORY}/kc:${{ github.sha }} --tag ghcr.io/${REPOSITORY}/kc:latest --platform linux/amd64 --push --progress plain
      env:
        REPOSITORY: ${{ github.repository }}

